/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Modified by Plutext Pty Ltd for the docx4j FO renderer (docx4j-fo-renderer), a modified distribution derived from
 * Apache FOP 2.11: hook column-widths, a width and a gap per column (fop/CR-026). See README.md, "Changes from Apache
 * FOP 2.11". */

/* $Id$ */

package org.apache.fop.area;

import java.util.List;

import org.apache.fop.fo.pagination.RegionBody;
import org.apache.fop.traits.WritingModeTraitsGetter;

/**
 * This class is a container for the areas that may be generated by
 * an fo:region-body.  It extends the RegionReference that is used
 * directly by the other region classes.
 * See fo:region-body definition in the XSL Rec for more information.
 */
public class BodyRegion extends RegionReference {

    private static final long serialVersionUID = -1848872997724078080L;

    private BeforeFloat beforeFloat;  // optional
    private MainReference mainReference; // mandatory
    private Footnote footnote; // optional
    private int columnGap;
    private int columnCount;
    private int[] columnWidths; // hook column-widths (fop/CR-026): per column, or null for equal columns
    private int[] columnGaps; // per pair of columns

    /**
     * Constructor which can read traits directly
     * from an fo:region-body formatting object.
     * @param rb the region-body FO node
     * @param parent the parent region viewport
     */
    public BodyRegion(RegionBody rb, RegionViewport parent) {
        this(rb.getNameId(), rb.getRegionName(), parent, rb.getColumnCount(), rb.getColumnGap());
    }

    /**
     * Constructor which can read traits directly
     * from an fo:region-body formatting object.
     * @param regionClass the region class (as returned by Region.getNameId())
     * @param regionName the name of the region (as returned by Region.getRegionName())
     * @param parent the parent region viewport
     * @param columnCount the number of columns
     * @param columnGap the gap between columns
     */
    public BodyRegion(int regionClass, String regionName, RegionViewport parent,
            int columnCount, int columnGap) {
        super(regionClass, regionName, parent);
        this.columnCount = columnCount;
        this.columnGap = columnGap;
        mainReference = new MainReference(this);
    }

    /**
     * Get the number of columns when not spanning
     *
     * @return the number of columns
     */
    public int getColumnCount() {
        return this.columnCount;
    }

    /** @return the column-gap value */
    public int getColumnGap() {
        return this.columnGap;
    }

    int getContentIPD() {
        RegionViewport rv = getRegionViewport();
        return getIPD() - rv.getBorderAndPaddingWidthStart() - rv.getBorderAndPaddingWidthEnd();
    }

    /**
     * The inline size of a column: with equal columns, of each; with hook column-widths (fop/CR-026), of the
     * first.
     * @return the first column's inline size in millipoints
     */
    public int getColumnIPD() {
        return getColumnWidth(0);
    }

    /**
     * Hook column-widths (fop/CR-026): gives the columns their widths and gaps, as the fo:region-body's
     * fox:column-widths and fox:column-gaps resolved for this page.
     * @param widths a width per column, or null for equal columns
     * @param gaps a gap per pair of columns, or null
     */
    public void setColumnWidths(int[] widths, int[] gaps) {
        this.columnWidths = widths;
        this.columnGaps = gaps;
    }

    /**
     * Hook column-widths (fop/CR-026): resolves the fo:region-body's column widths against this region's
     * content inline size, once it is set.
     * @param rb the fo:region-body
     */
    public void resolveColumnWidths(RegionBody rb) {
        int[] widths = rb.resolveColumnWidths(getContentIPD());
        setColumnWidths(widths, widths == null ? null : rb.getColumnGaps());
    }

    /** @return a width per column, or null for equal columns (hook column-widths, fop/CR-026) */
    public int[] getColumnWidths() {
        return columnWidths;
    }

    /** @return a gap per pair of columns, or null for equal columns (hook column-widths, fop/CR-026) */
    public int[] getColumnGaps() {
        return columnGaps;
    }

    /**
     * @param col a zero-based column
     * @return that column's inline size in millipoints (hook column-widths, fop/CR-026)
     */
    public int getColumnWidth(int col) {
        if (columnWidths != null) {
            return columnWidths[col];
        }
        return (getContentIPD() - (columnCount - 1) * columnGap) / columnCount;
    }

    /**
     * @param col a zero-based column
     * @return the gap after that column in millipoints (hook column-widths, fop/CR-026)
     */
    public int getColumnGap(int col) {
        if (columnGaps != null && columnGaps.length > 0) {
            return columnGaps[Math.min(col, columnGaps.length - 1)];
        }
        return columnGap;
    }

    /**
     * Get the main reference area.
     *
     * @return the main reference area
     */
    public MainReference getMainReference() {
        return mainReference;
    }

    /**
     * indicates whether the main reference area has any child areas added to it
     *
     * @return whether the main reference area has any child areas added to it
     */
    public boolean isEmpty() {
        return (mainReference == null || mainReference.isEmpty())
               && (footnote == null || footnote.isEmpty())
               && (beforeFloat == null || beforeFloat.isEmpty());
    }


    /**
     * Get the before float area.
     *
     * @return the before float area
     */
    public BeforeFloat getBeforeFloat() {
        if (beforeFloat == null) {
            beforeFloat = new BeforeFloat();
        }
        return beforeFloat;
    }

    /**
     * Get the footnote area.
     *
     * @return the footnote area
     */
    public Footnote getFootnote() {
        if (footnote == null) {
            footnote = new Footnote();
        }
        return footnote;
    }

    /**
     * @return the available BPD in the main reference area after the previous span reference
     * areas are subtracted.
     */
    public int getRemainingBPD() {
        int usedBPD = 0;
        List<Span> spans = getMainReference().getSpans();
        int previousSpanCount = spans.size() - 1;
        for (int i = 0; i < previousSpanCount; i++) {
            usedBPD += spans.get(i).getHeight();
        }
        return getBPD() - usedBPD;
    }

    /**
     * Sets the writing mode traits for the main reference area of
     * this body region area.
     * @param wmtg a WM traits getter
     */
    public void setWritingModeTraits(WritingModeTraitsGetter wmtg) {
        if (getMainReference() != null) {
            getMainReference().setWritingModeTraits(wmtg);
        }
    }

    /** {@inheritDoc} */
    public Object clone() throws CloneNotSupportedException {
        BodyRegion br = (BodyRegion) super.clone();
        br.mainReference = new MainReference(br);
        br.mainReference.setSpans(mainReference.getSpans());
        return br;
    }

}
